version: '3'

services:
  demo1:
    image: enschede/docker-demo1:0.0.1-SNAPSHOT
    deploy:
      update_config:
        parallelism: 1
        delay: 15s
#      placement:
#        constraints:
#          - node.role == worker
      replicas: 1
      labels:
      - traefik.docker.network=traefik-net
      - traefik.port=8080
      - traefik.enable=true
    networks:
      - default
      - traefik-net
  demo2:
    image: enschede/docker-demo2:0.0.1-SNAPSHOT
    deploy:
      update_config:
        parallelism: 1
        delay: 15s
#      placement:
#        constraints:
#          - node.role == worker
      replicas: 1
#      labels:
#      - traefik.docker.network=traefik-net
#      - traefik.port=8080
#      - traefik.enable=true
    networks:
      - default

networks:
  default:
    driver: overlay
  traefik-net:
    external: true