version: '3'

# Starten:
# 2. docker network create -d overlay my-overlay
# 1. docker stack deploy -c docker-compose.yaml demo1

services:
  node1:
    image: enschede/docker-node1:0.0.1-SNAPSHOT
    deploy:
      update_config:
        parallelism: 1
        delay: 15s
      placement:
        constraints:
          - node.role == worker
      replicas: 1
      labels:
      - traefik.docker.network=traefik-net
      - traefik.port=8080
      - traefik.enable=true
    networks:
      - default
      - traefik-net
  node2:
    image: enschede/docker-node2:0.0.1-SNAPSHOT
    deploy:
      update_config:
        parallelism: 1
        delay: 15s
      placement:
        constraints:
          - node.role == worker
      replicas: 1
    networks:
      - default

networks:
  default:
    driver: overlay
  traefik-net:
    external: true
