version: '3.3'

services:
  node1:
    image: enschede/docker-node1:0.0.1-SNAPSHOT
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 2
      update_config:
        parallelism: 1
        delay: 15s
      restart_policy:
        condition: on-failure
    ports:
      - "8081:8080"

  node2:
    image: enschede/docker-node2:0.0.1-SNAPSHOT
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 5
      update_config:
        parallelism: 1
        delay: 15s
      restart_policy:
        condition: on-failure
