logLevel = "DEBUG"

defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    # Volgende 2 regels zijn optioneel en verzorgen redirect naar
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      # Volgende 3 regels mogen herhaald worden, bij meerdere certificaten wordt gematcht
      [[entryPoints.https.tls.certificates]]
      certFile = "/ssl/server.pem"
      keyFile = "/ssl/server-key.pem"

[web]
address = ":8080"
certFile = "/ssl/server.pem"
keyFile = "/ssl/server-key.pem"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "marcenschede.nl"
watch = true
swarmmode = true
exposedbydefault = false