logLevel = "DEBUG"

defaultEntryPoints = ["http"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
#  [entryPoints.https]
#  address = ":443"
#    [entryPoints.https.tls]
#      [[entryPoints.https.tls.certificates]]
#      certFile = "/ssl/server.pem"
#      keyFile = "/ssl/server-key.pem"

[web]
address = ":8080"
certFile = "/ssl/server.pem"
keyFile = "/ssl/server-key.pem"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "marcenschede.nl"
watch = true
swarmmode = true
exposedbydefault = false